server.port: @server.port@

spring:
  application:
    name: @name@
    description: @description@
  flyway.schemas: hook

kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  client-id: hooker
  ssl:
    enabled: false
    trust-store-location: "test"
    trust-store-password: "test"
    key-store-location: "test"
    key-store-password: "test"
    key-password: "test"
    key-store-type: PKCS12
    trust-store-type: PKCS12
  consumer:
    concurrency: 8
    group-id: "HookerListener"
    enable-auto-commit: false
    auto-offset-reset: earliest
    max-poll-records: 20
  topics:
    invoice:
      id: mg-invoice-100-2
      enabled: false

info:
  version: @version@
  responsible: Inal Arsanukaev
  stage: dev
  damsel.version: @damsel.version@

bm.pooling:
  url: http://localhost:8022/repo
  maxPoolSize: 1
  delay: 5000
  maxQuerySize: 500

service:
  invoicing:
    url: http://hellgate:8022/v1/processing/invoicing
    networkTimeout: 5000
  customer:
    url: http://hellgate:8022/v1/processing/customer
    networkTimeout: 5000

cache:
  invoice:
    size: 10000

# connection timeout
merchant.callback.timeout: 10

spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: org.postgresql.Driver
  url: @db.url@
  username: @db.user@
  password: @db.password@
  hikari:
    maximum-pool-size: 10
    idle-timeout: 30000
    data-source-properties:
      reWriteBatchedInserts: true

db:
  jdbc:
    tr_timeout: 300000

message:
  scheduler.delay: 1000
  sender.number: 10

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
