server.port: @server.port@

spring:
  application:
    name: '@name@'
    description: @description@
  flyway:
    schemas: hook
    table: schema_version

kafka:
  bootstrap-servers: kenny-kafka1.bst1.rbkmoney.net:9092
  client-id: hooker
  ssl:
    enabled: false
    trust-store-location: "test"
    trust-store-password: "test"
    key-store-location: "test"
    key-store-password: "test"
    key-password: "test"
    key-store-type: PKCS12
    trust-store-type: PKCS12
  consumer:
    group-id: "HookerListener"
    enable-auto-commit: false
    auto-offset-reset: earliest
    max-poll-records: 20
  topics:
    invoice:
      id: mg-invoice-100-2
      enabled: false
      concurrency: 8
    customer:
      id: mg-events-customer
      enabled: false
      concurrency: 1

info:
  version: @version@
  responsible: Inal Arsanukaev
  stage: dev
  damsel.version: @damsel.version@

service:
  invoicing:
    url: http://hellgate:8022/v1/processing/invoicing
    networkTimeout: 5000
  customer:
    url: http://hellgate:8022/v1/processing/customer_management
    networkTimeout: 5000

cache:
  invoice:
    size: 10000

# connection timeout
merchant.callback.timeout: 10

limit:
  perShop: 10
  perParty: 5

spring.datasource:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: org.postgresql.Driver
  url: @db.url@
  username: @db.user@
  password: @db.password@
  hikari:
    maximum-pool-size: 10
    idle-timeout: 30000
    data-source-properties:
      reWriteBatchedInserts: true

db:
  jdbc:
    tr_timeout: 300000

message:
  scheduler:
    delay: 1000
    threadPoolSize: 10
    limit: 50

clean:
  scheduler:
    cron: "0 0 * * * *"
    timezone: Europe/Moscow
    daysAgo: 30

management:
  security:
    flag: false
  server:
    port: 8023
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
      prometheus:
        enabled: true